name: esc_pos_printer_forked_v
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charset_converter: ^2.0.0
  esc_pos_utils: ^1.1.0
  intl: 0.18.1
  ping_discover_network_forked: 0.0.1
  flutter:
    sdk: flutter
  # esc_pos_utils:
  #   path: ../esc_pos_utils
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
