name: esc_pos_printer_forked_v
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer
publish_to: none

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_esc_pos_utils:
    git:
      url: https://github.com/Bilonik/flutter_esc_pos_utils
      ref: main
  intl: 0.19.0
  ping_discover_network_forked: 0.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
